spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  server:
    port: 8088
    tomcat:
      uri-encoding: UTF-8
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  redis:
    host: 120.79.91.131
    port: 6379
    database: 6
    password: yniotredis
  datasource:
    url: jdbc:mysql://120.79.91.131:3306/lms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: lms_admin
    password: lms_admin
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      minIdle: 3
      maxActive: 20
      maxWait: 6000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create

#logging:
#  config: classpath:logback-boot.xml
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value:true # 逻辑已删除值(默认为 1)
      logic-not-delete-value: false # 逻辑未删除值(默认为 0)