spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  server:
    port: 8080
    tomcat:
      uri-encoding: UTF-8
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  redis:
    host: 120.79.91.131
    port: 6379
    database: 6
    password: yniotredis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://120.79.91.131:3306/lms
      username: lms_admin
      password: lms_admin
      initial-size: 1
      min-idle: 5
      max-active: 50
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true

logging:
  config: classpath:logback-boot.xml
mybatis-plus:
  mapper-locations: classpath*:com/yniot/lms/db/**/*.xml
#  global-config:
#    db-config:
#      logic-delete-value:true # 逻辑删除
#      logic-not-delete-value: false # 逻辑删除
#微信配置
wechat:
  public:
    
  auth:
    path:wechat
  smallapp:
    configs:
      - appid: wx935f4f8a4ba9454b
        secret: b3fbd40446090e3b5672caed753ca21d
        token: lms_token
        aesKey:
        msgDataFormat: JSON
  pay:
    appId: wx935f4f8a4ba9454b
    mchId: 1520972321
    mchKey: 16919618d52de660a750f5466e26eb3b
    keyPath: classpath*:com/yniot/lms/config/apiclient_cert.p12
# 短信配置
message:
  aliyun:
    accessKeyId: LTAI6zmwosr9fzp9
    accessKeySecret: viraMBYDvSrGTC4PJJrw7ExTkdn0kf
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    connectTimeout: 10000
    readTimeout: 1000
    signName: 有你物联网科技
    regionId: cn-hangzhou